;;; stylus-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from stylus-mode.el

(autoload 'stylus-mode "stylus-mode" "\
Major mode for editing stylus node.js templates

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.styl\\'" . stylus-mode))
(register-definition-prefixes "stylus-mode" '("stylus-"))

;;; End of scraped data

(provide 'stylus-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; stylus-mode-autoloads.el ends here
