;;; sws-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sws-mode.el

(autoload 'sws-mode "sws-mode" "\
Major mode for editing significant whitespace files

(fn)" t)
(register-definition-prefixes "sws-mode" '("sws-"))

;;; End of scraped data

(provide 'sws-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sws-mode-autoloads.el ends here
